library;

import 'dart:convert';
import 'dart:io';

import 'package:audioplayers/audioplayers.dart';
import 'package:crypto/crypto.dart';
import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:path_provider/path_provider.dart';

/// This represents a single CacheAudioPlayerPlus, which can play one audio at
/// a time. To play several audios at the same time, you must create several
/// instances of this class.
///
/// It holds methods to play, loop, pause, stop, seek the audio, and some
/// useful hooks for handlers and callbacks. It also exposes helpers to manage
/// the on-disk audio cache (pre-caching, clearing, inspecting size, etc.).
class CacheAudioPlayerPlus {
  final AudioPlayer _audioPlayer = AudioPlayer();

  /// Name of the internal Hive box used to store the cache index (url → path).
  static const String _cacheBoxName = 'cacheAudioPlayerPlus';

  /// Tracks whether [init] has already initialized Hive. Safe guard for
  /// multiple calls.
  static bool _hiveInitialized = false;

  /// Optional one-shot initializer. Call this once from your `main()` before
  /// `runApp(...)` to make sure Hive is ready and the cache box is opened:
  ///
  /// ```dart
  /// Future<void> main() async {
  ///   WidgetsFlutterBinding.ensureInitialized();
  ///   await CacheAudioPlayerPlus.init();
  ///   runApp(const MyApp());
  /// }
  /// ```
  ///
  /// Calling this is optional — if you skip it, the library will lazily
  /// initialize Hive the first time a cache-aware method is used. However,
  /// calling it explicitly is recommended to avoid any first-call latency
  /// and to ensure a predictable startup order.
  static Future<void> init() async {
    if (_hiveInitialized && Hive.isBoxOpen(_cacheBoxName)) return;
    try {
      await Hive.initFlutter();
    } catch (_) {
      // Hive may already be initialized by the host app — that's fine.
    }
    if (!Hive.isBoxOpen(_cacheBoxName)) {
      await Hive.openBox(_cacheBoxName);
    }
    _hiveInitialized = true;
  }

  /// Returns the cache box, lazily initializing Hive if [init] was never
  /// called. This keeps the public API backwards compatible: existing users
  /// who never called [init] will still get a working cache.
  Future<Box> _getCacheBox() async {
    if (Hive.isBoxOpen(_cacheBoxName)) {
      return Hive.box(_cacheBoxName);
    }
    try {
      return await Hive.openBox(_cacheBoxName);
    } catch (_) {
      // Hive was probably not initialized yet.
      await Hive.initFlutter();
      _hiveInitialized = true;
      return await Hive.openBox(_cacheBoxName);
    }
  }

  /// Derives the cache key for a given URL. The cache key is generated by
  /// hashing the full URL with MD5, guaranteeing a unique, fixed-length key
  /// per distinct URL.
  ///
  /// Earlier releases of this package derived the key from only the last
  /// path segment (e.g. `track.mp3`), which caused cache collisions when
  /// different URLs shared the same filename but lived under different
  /// paths (e.g. `https://a.com/x/track.mp3` and `https://a.com/y/track.mp3`
  /// both resolved to the same key `track.mp3`). Hashing the full URL
  /// guarantees each distinct URL maps to its own cache entry.
  String _cacheKeyFromUrl(String url) {
    // Encode the URL string to bytes so it can be fed into the MD5 hasher.
    final bytes = utf8.encode(url);

    // Hash the full URL (not just the filename) so two different URLs can
    // never collide into the same cache key, even if their filenames match.
    return md5.convert(bytes).toString();
  }

  /// get Current State of the Player
  /// initial state, stop has been called or an error occurred.
  ///  stopped,
  ///
  /// Currently playing audio.
  /// playing,
  ///
  /// Pause has been called.
  /// paused,
  ///
  /// The audio successfully completed (reached the end).
  /// completed,
  ///
  /// The player has been disposed and should not be used anymore.
  /// disposed,
  PlayerState get state => _audioPlayer.state;

  /// Stream of changes on player state.
  Stream<PlayerState> get onPlayerStateChanged =>
      _audioPlayer.onPlayerStateChanged;

  /// Stream of changes on audio position.
  ///
  /// Roughly fires every 200 milliseconds. Will continuously update the
  /// position of the playback if the status is [PlayerState.playing].
  ///
  /// You can use it on a progress bar, for instance.
  Stream<Duration> get onPositionChanged => _audioPlayer.onPositionChanged;

  /// Stream of changes on audio duration.
  ///
  /// An event is going to be sent as soon as the audio duration is available
  /// (it might take a while to download or buffer it).
  Stream<Duration> get onDurationChanged => _audioPlayer.onDurationChanged;

  /// Stream of player completions.
  ///
  /// Events are sent every time an audio is finished, therefore no event is
  /// sent when an audio is paused or stopped.
  ///
  /// [ReleaseMode.loop] also sends events to this stream.
  Stream get onPlayerComplete => _audioPlayer.onPlayerComplete;

  /// Stream of seek completions.
  ///
  /// An event is going to be sent as soon as the audio seek is finished.
  Stream get onSeekComplete => _audioPlayer.onSeekComplete;

  Stream<String> get onLog => _audioPlayer.onLog;

  ///playing  network audio directly from string url
  ///you can enable and disable caching by passing cache default is true
  ///
  /// When [cache] is true, the file is downloaded on first playback and
  /// stored locally. All subsequent calls with the same URL play straight
  /// from disk with no network activity.
  ///
  /// Provide [onDownloadProgress] to observe download progress the first
  /// time a file is fetched (it won't fire on cache hits).
  Future playerNetworkAudio({
    required String url,
    bool cache = true,
    double? volume,
    double? balance,
    AudioContext? ctx,
    Duration? position,
    PlayerMode? mode,
    void Function(int received, int total)? onDownloadProgress,
  }) async {
    if (cache) {
      Box cacheBox = await _getCacheBox();
      String urlAsKey = _cacheKeyFromUrl(url);
      final cachedPath = cacheBox.get(urlAsKey);
      if (cachedPath is String && File(cachedPath).existsSync()) {
        await _audioPlayer.play(
          DeviceFileSource(cachedPath),
          volume: volume,
          position: position,
          balance: balance,
          ctx: ctx,
          mode: mode,
        );
        return;
      }
      try {
        Directory appDocDir = await getApplicationDocumentsDirectory();
        String audioFilePath = '${appDocDir.path}/$urlAsKey';
        await Dio().download(
          url,
          audioFilePath,
          onReceiveProgress: onDownloadProgress,
        );
        await cacheBox.put(urlAsKey, audioFilePath);
        await _audioPlayer.play(
          DeviceFileSource(audioFilePath),
          volume: volume,
          position: position,
          balance: balance,
          ctx: ctx,
          mode: mode,
        );
      } catch (e) {
        debugPrint('Error ${e.toString()}');
        debugPrint('Please Report This Error To The Developer Of This Package');
      }
    } else {
      try {
        await _audioPlayer.play(
          UrlSource(url),
          volume: volume,
          position: position,
          balance: balance,
          ctx: ctx,
          mode: mode,
        );
      } catch (e) {
        debugPrint('Error ${e.toString()}');
        debugPrint('Please Report This Error To The Developer Of This Package');
      }
    }
  }

  /// Plays an audio file that already lives on the device's file system.
  ///
  /// Useful when you manage caching yourself or need to play a recording
  /// the user just made.
  Future<void> playLocalAudio({
    required String filePath,
    double? volume,
    double? balance,
    AudioContext? ctx,
    Duration? position,
    PlayerMode? mode,
  }) async {
    try {
      await _audioPlayer.play(
        DeviceFileSource(filePath),
        volume: volume,
        position: position,
        balance: balance,
        ctx: ctx,
        mode: mode,
      );
    } catch (e) {
      debugPrint('playLocalAudio error: ${e.toString()}');
    }
  }

  /// Plays an audio file bundled as a Flutter asset.
  ///
  /// [assetPath] is resolved relative to your `pubspec.yaml` assets section,
  /// e.g. `sounds/ding.mp3`.
  Future<void> playAssetAudio({
    required String assetPath,
    double? volume,
    double? balance,
    AudioContext? ctx,
    Duration? position,
    PlayerMode? mode,
  }) async {
    try {
      await _audioPlayer.play(
        AssetSource(assetPath),
        volume: volume,
        position: position,
        balance: balance,
        ctx: ctx,
        mode: mode,
      );
    } catch (e) {
      debugPrint('playAssetAudio error: ${e.toString()}');
    }
  }

  // --------------------------------------------------------------------------
  //  Cache management
  // --------------------------------------------------------------------------

  /// Returns `true` when the given [url] has already been downloaded and the
  /// cached file still exists on disk.
  Future<bool> isCached(String url) async {
    final box = await _getCacheBox();
    final path = box.get(_cacheKeyFromUrl(url));
    if (path is! String) return false;
    return File(path).existsSync();
  }

  /// Returns the local file path for a cached [url], or `null` if the URL
  /// is not cached (or the underlying file was deleted externally).
  Future<String?> getCachedFilePath(String url) async {
    final box = await _getCacheBox();
    final path = box.get(_cacheKeyFromUrl(url));
    if (path is! String) return null;
    if (!File(path).existsSync()) return null;
    return path;
  }

  /// Downloads and stores an audio file in the cache without playing it.
  ///
  /// This is handy for "pre-warming" the cache (e.g. fetching the next track
  /// in a playlist) so that subsequent playback is instant. If the file is
  /// already cached, the existing path is returned and no network request
  /// is issued.
  ///
  /// Returns the local file path of the cached file, or `null` on failure.
  Future<String?> preCacheAudio({
    required String url,
    void Function(int received, int total)? onDownloadProgress,
  }) async {
    try {
      final box = await _getCacheBox();
      final key = _cacheKeyFromUrl(url);
      final existing = box.get(key);
      if (existing is String && File(existing).existsSync()) {
        return existing;
      }
      final Directory appDocDir = await getApplicationDocumentsDirectory();
      final String audioFilePath = '${appDocDir.path}/$key';
      await Dio().download(
        url,
        audioFilePath,
        onReceiveProgress: onDownloadProgress,
      );
      await box.put(key, audioFilePath);
      return audioFilePath;
    } catch (e) {
      debugPrint('preCacheAudio error: ${e.toString()}');
      return null;
    }
  }

  /// Removes the cached audio for a single [url]: deletes the file on disk
  /// and removes the entry from the cache index.
  Future<void> clearCacheForUrl(String url) async {
    final box = await _getCacheBox();
    final key = _cacheKeyFromUrl(url);
    final path = box.get(key);
    if (path is String) {
      final f = File(path);
      if (await f.exists()) {
        try {
          await f.delete();
        } catch (_) {}
      }
    }
    await box.delete(key);
  }

  /// Removes every cached audio file this package knows about and empties
  /// the cache index. Call this if you want to reclaim disk space or give
  /// the user a "clear downloads" button.
  Future<void> clearCache() async {
    final box = await _getCacheBox();
    for (final key in box.keys.toList()) {
      final path = box.get(key);
      if (path is String) {
        final f = File(path);
        if (await f.exists()) {
          try {
            await f.delete();
          } catch (_) {}
        }
      }
    }
    await box.clear();
  }

  /// Returns the total size, in bytes, of every audio file currently cached
  /// by this package. Files missing from disk are silently ignored.
  Future<int> getCacheSize() async {
    final box = await _getCacheBox();
    int total = 0;
    for (final key in box.keys) {
      final path = box.get(key);
      if (path is String) {
        final f = File(path);
        if (await f.exists()) {
          try {
            total += await f.length();
          } catch (_) {}
        }
      }
    }
    return total;
  }

  /// Returns all cache keys currently stored in the cache index. By default
  /// the key is the last segment of the URL (the file name).
  Future<List<String>> getCachedKeys() async {
    final box = await _getCacheBox();
    return box.keys.map((e) => e.toString()).toList();
  }

  // --------------------------------------------------------------------------
  //  Playback controls (pass-through to audioplayers)
  // --------------------------------------------------------------------------

  /// Stops the audio that is currently playing.
  ///
  /// The position is going to be reset and you will no longer be able to resume
  /// from the last point.
  Future<void> stop() async {
    await _audioPlayer.stop();
  }

  /// Pauses the audio that is currently playing.
  ///
  /// If you call [resume] later, the audio will resume from the point that it
  /// has been paused.
  Future<void> pause() async {
    await _audioPlayer.pause();
  }

  /// Resumes the audio that has been paused or stopped.
  Future<void> resume() async {
    await _audioPlayer.resume();
  }

  /// Releases the resources associated with this media player.
  ///
  /// The resources are going to be fetched or buffered again as soon as you
  /// call [resume] or change the source.
  Future<void> release() async {
    await _audioPlayer.release();
  }

  /// Moves the cursor to the desired position.
  Future<void> seek(Duration position) async {
    await _audioPlayer.seek(position);
  }

  Future<void> setAudioContext(AudioContext ctx) async {
    await _audioPlayer.setAudioContext(ctx);
  }

  Future<void> setPlayerMode(PlayerMode mode) async {
    await _audioPlayer.setPlayerMode(mode);
  }

  /// Sets the stereo balance.
  ///
  /// -1 - The left channel is at full volume; the right channel is silent.
  ///  1 - The right channel is at full volume; the left channel is silent.
  ///  0 - Both channels are at the same volume.
  Future<void> setBalance(double balance) async {
    await _audioPlayer.setBalance(balance);
  }

  /// Sets the volume (amplitude).
  ///
  /// 0 is mute and 1 is the max volume. The values between 0 and 1 are linearly
  /// interpolated.
  Future<void> setVolume(double volume) async {
    await _audioPlayer.setVolume(volume);
  }

  /// Sets the release mode.
  ///
  /// Check [ReleaseMode]'s doc to understand the difference between the modes.
  Future<void> setReleaseMode(ReleaseMode releaseMode) async {
    await _audioPlayer.setReleaseMode(releaseMode);
  }

  /// Sets the playback rate - call this after first calling play() or resume().
  ///
  /// iOS and macOS have limits between 0.5 and 2x
  /// Android SDK version should be 23 or higher
  Future<void> setPlaybackRate(double playbackRate) async {
    await _audioPlayer.setPlaybackRate(playbackRate);
  }

  /// Get audio duration after setting url.
  /// It will be available as soon as the audio duration is available
  /// (it might take a while to download).
  Future<Duration?> getDuration() async {
    return _audioPlayer.getDuration();
  }

  // Gets audio current playing position
  Future<Duration?> getCurrentPosition() async {
    return _audioPlayer.getCurrentPosition();
  }

  /// You must call this method when your [CacheAudioPlayerPlus] instance is not going to
  /// be used anymore. If you try to use it after this you will get errors.
  Future<void> dispose() async {
    // First stop and release all native resources.
    _audioPlayer.dispose();
  }
}
